### ISSUE TITLE
Logging hot-deskers doesn't happen if the WiFi/Google is down

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/logcards#2]
Today (for example), none of the hot-deskers tapping in have been recorded.  I'm assuming that's because the Doorbot either (a) isn't connected to the Internet too well, or (b) Google docs submissions haven't worked properly.  I can ssh into doorbot1 (and Patrick had also done so earlier this morning).

Both Ronan and Jyl have been logged today in visits.log, but neither of them on the Google spreadsheet (I've just done it manually).

**Comment by johnmckerrell** [comment]
The HTTP request isn't working, you seem to have got some of the CURL command line options in the URL, but that's because it was originally posting data so you'll need to strip the URL down to just the URL and then post the data from ruby side.

I would suggest that it's not worth having two sets of HTTP code, you could always add the user's name to unloggedFile, and then loop over it.

For testing you should be ok to submit test data, ideally use a name that's clearly testing and let us know when you're done.

**Comment by johnmckerrell** [comment]
Ok, just tested b2afd9f and happy enough that it's fixed the bug, thanks!
